language: node_js
sudo: required
services:
  # specifies docker as a dependancy
  - docker # will be started on Travis-CI Server
  - heroku

before_install: # commands executed before our tests are run
  # build our React app
  - docker build -t tzetzo/react-test -f ./client/Dockerfile.dev ./client
  # build any other app that has tests

script:
  # tests will be run for every github branch!
  # run our React app tests
  - docker run -e CI=true tzetzo/react-test npm run test
  # run any other app tests

# after all tests have successfully finished
# build Production Images for each of our services
after_success:
  - docker build -t tzetzo/multi_docker-react ./client # uses Dockerfile by default
  - docker build -t tzetzo/multi_docker-node ./server
  - docker build -t tzetzo/multi_docker-worker ./worker
  - docker build -t tzetzo/multi_docker-nginx ./nginx
  # Log in to the docker CLI
  # the password & ID are setup as Env Vars inside https://travis-ci.org for the project
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push the above Images to Docker Hub
  - docker push tzetzo/multi_docker-react
  - docker push tzetzo/multi_docker-node
  - docker push tzetzo/multi_docker-worker
  - docker push tzetzo/multi_docker-nginx

  # Deployment to Heroku
  # Login to the Heroku Registry with Docker
  # Heroku Authorization token "5747991c-6c13-44be-9f1a-213562da815d"
  # - docker login --username="$HEROKU_USERNAME" --password="$HEROKU_PASSWORD" registry.heroku.com
  - echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
  # - heroku container:login
  # Tag Docker Hub Image & push it to Heroku Registry - https://devcenter.heroku.com/articles/container-registry-and-runtime
  # - docker tag tzetzo/multi_docker-react registry.heroku.com/multi_docker-react/react
  # - docker push registry.heroku.com/multi_docker-react/react
  # - heroku stack:set container --app multi_docker-react
  # - heroku container:release react --app multi_docker-react

  # - docker tag tzetzo/multi_docker-node registry.heroku.com/multi_docker-node/node
  # - docker push registry.heroku.com/multi_docker-node/node

  # - docker tag tzetzo/multi_docker-worker registry.heroku.com/multi_docker-worker/worker
  # - docker push registry.heroku.com/multi_docker-worker/worker

  - docker tag tzetzo/multi_docker-nginx registry.heroku.com/tzetzo-multi-docker/web
  - docker push registry.heroku.com/tzetzo-multi-docker/web
  # - heroku stack:set container --app multi_docker-nginx
  - heroku container:release web --app tzetzo-multi-docker
  
  # - heroku container:release web node react worker

before_deploy: "echo 'ready Tzetzo?'"
# GitBash - heroku stack:set container
# heroku.yml & default.conf.template needed
deploy:
  provider: heroku
  api_key:
    # GitBash - "travis encrypt $(heroku auth:token)" - https://docs.travis-ci.com/user/deployment/heroku/
    secure: "RCeNgqO/bolmtn0aGXRqx4kU0egYZlWp/YQVwYCu36PjgQ/t2JU49JqRn5qs12jZHIS6myHcgLevM5ACsSi47K/wfmsQhREzHW8JAFQHXn9S5PXf8Ynj8VSDbheo6bWU3Kx0hjmPTYeT1mpK2/932CTEjHhmT1Zs7OVyvKe1Ga3hcAwOJnhyEBky7DkMn07A/dDboZo44YQgnFnVqE79lKs2hA64FEzeDV4qQwaFSdq6JmGnrKZWvKQ1OT+aiRAfTRJj98V7en+APWHE/ovMwVPADUjJLA/AUebrWa1KlWIMF2zhb1GU4z2/dng8QwfwmX+f/F1sMRFoGj6VrI22I3LI0kTiwQwiUkqAJQONfVPfC9z+4kMxaVUbiSY2WYjiazQbb/i0a/zQbsLiNbOV6pgvCbK0DsNVH0O6ysQofKE3MP3W+H3jkQPXPhOuQJbWyQpomSeX2xYL8dxOTAPDCbflTrqQmUoSpM5NixMuhZnAN+ry0EbrtzMdnoPwyJC4EwBRzICv1vQ7SqYr2gFLT7jEFLWJ52E0Gs1WhNCBglBvg5ASa/yCtSJZ/VAOoRU70FMIe2uhGsw/pGHPCdrpLYSDwa0hQkmaO8O3yQ07d4NiNUFa+HtmcZR/jWB69Ltxv9n2T6fBoV/iUI91nLyTxJAMZPc8oA5VTqV4KqZgdR4="
  # the name of the app in heroku
  app: tzetzo-multi-docker
  on:
    # repo name in github
    repo: tzetzo/multi-docker
    

after_deploy: "echo 'done Tzetzo?'"

# Deployment to AWS ElasticBeanstalk only when Master Branch changed!
# deploy:
#     #edge: true #add this if you are getting a persistent missing bucket_name error with a failed build
#     provider: elasticbeanstalk
#     region: us-west-2
#     app: multi-docker
#     env: MultiDocker-env
#     bucket_name: elasticbeanstalk-us-west-2-306476627547
#     bucket_path: docker-multi
#     on:
#         branch: master
#     # The following keys are from AWS IAM & their values are saved inside https://travis-ci.org - Settings - Environment Variables
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY
