#!/bin/bash
echo "$HEROKU_PASSWORD" | docker login -u "$HEROKU_USERNAME" --password-stdin registry.heroku.com
docker tag tzetzo/multi_docker-nginx registry.heroku.com/multi_docker-nginx/web
docker push registry.heroku.com/multi_docker-nginx/web
